name: "🐛 Bug 报告"
description: "报告一个错误或意外行为"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您提交 Bug 报告！请尽可能详细地填写以下信息，以便我们能够更快地修复问题。

  - type: textarea
    id: description
    attributes:
      label: "问题描述"
      description: "请清晰简洁地描述您遇到的问题。"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "重现步骤"
      description: "请提供重现该 Bug 的步骤："
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "预期行为"
      description: "请描述您期望应用程序如何响应。"

  - type: textarea
    id: actual-behavior
    attributes:
      label: "实际行为"
      description: "请描述应用程序当前的实际行为。"

  - type: input
    id: environment
    attributes:
      label: "环境"
      description: "请提供您的操作系统。"
      placeholder: "例如：Windows 10"

  - type: textarea
    id: extra-context
    attributes:
      label: "补充说明"
      description: "任何其他可能有助于我们理解和解决问题的信息。"
